
DROP TABLE IF EXISTS INVOICE_TABLE;
CREATE TABLE INVOICE_TABLE (
  invoice_id INTEGER PRIMARY KEY AUTO_INCREMENT ,
  invoice_value DOUBLE NOT NULL,
  invoice_status VARCHAR(100) NOT NULL,
  order_name VARCHAR(20) NOT NULL
) ;